'use client';
import { EmptyState } from '@/components/shared/workflow/workflowFields';
import { TaskCardDialogContent } from '@/components/design-workflow/task/modal/taskCardDialogContent';
import { createTaskDetailModel } from '@/components/design-workflow/task/model/taskDetailModel';
import { TaskDetailPage } from '@/components/design-workflow/task/taskDetailPage';
import type { WorkflowController } from '@/utils/workflow/hooks/useWorkflowController';
export const WorkflowTaskDetail = ({
	model,
}: {
	model: Pick<
		WorkflowController,
		| 'taskBusy'
		| 'workflow'
		| 'task'
		| 'isManager'
		| 'taskCommentsPage'
		| 'taskActivityPage'
		| 'taskAddPanel'
		| 'selectedChecklistTemplate'
		| 'setSelectedChecklistTemplate'
		| 'setNewChecklistGroupTitle'
		| 'runPrimaryAction'
		| 'newChecklistGroupTitle'
		| 'addChecklist'
		| 'addChecklistItem'
		| 'messageFor'
		| 'newChecklistItemsByChecklist'
		| 'setNewChecklistItemsByChecklist'
		| 'selectedAnnotationAttachmentId'
		| 'reviewStateDraft'
		| 'updateTaskReviewState'
		| 'pendingReviewTaskId'
		| 'taskMutable'
		| 'createTaskVersion'
		| 'versionAttachmentId'
		| 'versionNotes'
		| 'versionApprovalState'
		| 'setVersionNotes'
		| 'setVersionApprovalState'
		| 'annotationBody'
		| 'createAttachmentAnnotation'
		| 'annotationVersionId'
		| 'annotationX'
		| 'annotationY'
		| 'annotationResolved'
		| 'setAnnotationBody'
		| 'setAnnotationResolved'
		| 'selectedTaskId'
		| 'labelFor'
		| 'cardTitleHeading'
		| 'modalTitleDraft'
		| 'setModalTitleDraft'
		| 'renameLockRef'
		| 'updateTaskState'
		| 'updateTask'
		| 't'
		| 'taskConflictNotice'
		| 'setReviewConfirmation'
		| 'submitReviewUpdate'
		| 'toggleTaskAddPanel'
		| 'archiveTask'
		| 'setTaskAddPanel'
		| 'setModalLabelComposerOpen'
		| 'setEditingLabelId'
		| 'labels'
		| 'workflowDataReady'
		| 'setEditingLabelName'
		| 'setEditingLabelColor'
		| 'modalLabelComposerOpen'
		| 'newLabelName'
		| 'setNewLabelName'
		| 'newLabelColor'
		| 'setNewLabelColor'
		| 'createLabel'
		| 'editingLabelId'
		| 'editingLabelName'
		| 'editingLabelColor'
		| 'updateLabelState'
		| 'updateLabel'
		| 'addChecklistState'
		| 'taskCoverLabel'
		| 'setTaskCoverLabel'
		| 'setTaskCoverFile'
		| 'taskCoverFile'
		| 'isPreparingTaskCover'
		| 'handleUploadTaskCover'
		| 'uploadTaskCoverState'
		| 'renderTaskAttachmentPicker'
		| 'reassignForm'
		| 'setReassignForm'
		| 'assignableUsers'
		| 'validReassignAssigneeSelected'
		| 'reassignTask'
		| 'reassignTaskState'
		| 'modalDescriptionEditing'
		| 'taskEditForm'
		| 'setTaskEditForm'
		| 'mentionableUsers'
		| 'taskUpdatePayload'
		| 'setModalDescriptionEditing'
		| 'taskEditBaselineRef'
		| 'chartTextColor'
		| 'dateFor'
		| 'deleteChecklist'
		| 'updateChecklistItem'
		| 'deleteChecklistItem'
		| 'addChecklistItemState'
		| 'taskMediaMutable'
		| 'setMediaDeleteTarget'
		| 'openAttachmentPreview'
		| 'handleSetAttachmentAsCover'
		| 'setTaskCoverFromAttachmentState'
		| 'commentBody'
		| 'setCommentBody'
		| 'addTaskComment'
		| 'addCommentState'
		| 'dateTimeFor'
		| 'describeWorkflowActivity'
		| 'taskDetailTab'
		| 'setTaskDetailTab'
		| 'reviewNotes'
		| 'setReviewNotes'
		| 'setVersionAttachmentId'
		| 'createTaskVersionState'
		| 'setSelectedAnnotationAttachmentId'
		| 'selectedAttachmentAnnotations'
		| 'setAnnotationVersionId'
		| 'setAnnotationX'
		| 'setAnnotationY'
		| 'createAnnotationState'
		| 'updateTaskStatus'
		| 'updateStatusState'
		| 'setTaskCommentsPage'
		| 'setTaskActivityPage'
	>;
}) => {
	if (model.taskBusy) return <EmptyState {...model.workflow.emptyStates.loadingTask} />;
	if (!model.task) return <EmptyState {...model.workflow.emptyStates.missingTask} />;
	const detail = createTaskDetailModel({ ...model, task: model.task });
	return model.selectedTaskId ? <TaskCardDialogContent model={detail} /> : <TaskDetailPage model={detail} />;
};
