export type Language = 'fr' | 'en';

export type TranslationDictionary = {
  common: {
    yes: string;
    no: string;
    save: string;
    cancel: string;
    delete: string;
    edit: string;
    view: string;
    actions: string;
    add: string;
    back: string;
    update: string;
    confirm: string;
    search: string;
    loading: string;
    refresh: string;
    retry: string;
    submit: string;
    close: string;
    display: string;
    selectValue: string;
    filterBy: string;
    dashboard: string;
    skipToContent: string;
      newItem: string;
      addImage: string;
      imageUploadHint: string;
      clickToEditCrop: string;
    noOptions: string;
    all: string;
    value: string;
    clearSelection: string;
    allMatchingSelected: (n: number) => string;
    pageElementsSelected: (n: number) => string;
    selectAllMatching: (n: number) => string;
    activeFiltersCount: (n: number) => string;
    validationErrorsDetected: string;
    appLogo: string;
    croppedPreview: string;
    togglePasswordVisibility: string;
  };
  filters: {
    contains: string;
    equals: string;
    startsWith: string;
    endsWith: string;
    isEmpty: string;
    isNotEmpty: string;
    is: string;
    between: string;
    from: string;
    to: string;
    addFilter: string;
    removeAllFilters: string;
    and: string;
    or: string;
  };
  navigation: {
    users: string;
    usersList: string;
    newUser: string;
    overview: string;
    board: string;
    projects: string;
    team: string;
    reports: string;
    notifications: string;
    myWork: string;
    profile: string;
    settings: string;
    myProfile: string;
    changePassword: string;
    logout: string;
    administration: string;
    productName: string;
    workspace: string;
    signedIn: string;
    collapseNavigation: string;
    expandNavigation: string;
    openInbox: string;
    noNotificationsYet: string;
    workflowUpdate: string;
    searchWorkspace: string;
    welcomeMale: string;
    welcomeFemale: string;
    welcomeNeutral: string;
  };
  workflow: {
    pageTitles: Record<string, string>;
    pageDescriptions: Record<string, string>;
    labels: Record<string, string>;
    buttons: Record<string, string>;
    metrics: Record<string, string>;
    statuses: Record<string, string>;
    priorities: Record<string, string>;
    activities: Record<string, string>;
    sections: Record<string, { title: string; description: string }>;
    emptyStates: Record<string, { title: string; description: string }>;
  };
  users: {
    firstName: string;
    lastName: string;
    email: string;
    gender: string;
    role: string;
    managerRole: string;
    designerRole: string;
    roleHelp: string;
    admin: string;
    active: string;
    inactive: string;
    registrationDate: string;
    lastUpdate: string;
    lastLogin: string;
    canView: string;
    canPrint: string;
    canCreate: string;
    canEdit: string;
    canDelete: string;
    deleteUser: string;
    deleteUserConfirm: string;
    addUser: string;
    updateUser: string;
    createUser: string;
    editUser: string;
    userDetails: string;
    avatar: string;
    profilePhoto: string;
    newUser: string;
    personalInfo: string;
    accountSettings: string;
    permissions: string;
    activeAccount: string;
    adminAccount: string;
    deleteUsers: (n: number) => string;
    male: string;
    female: string;
    userDeletedSuccess: string;
    userDeleteError: string;
    bulkDeleteUserBody: (n: number) => string;
    bulkUserDeletedSuccess: (n: number) => string;
    generalInfo: string;
    userNotFound: string;
    userUpdatedSuccess: string;
    userCreatedSuccess: string;
    userUpdateError: string;
    userCreateError: string;
    userFormStudio: string;
    createUserDescription: string;
    editUserDescription: string;
    userIdentity: string;
    adminRoleLocked: string;
    avatarCropped: string;
    validationErrorsDetected: string;
    fixValidationErrors: string;
    usersStudio: string;
    usersListDescription: string;
    usersRegister: string;
    totalUsers: string;
    activeUsers: string;
    adminUsers: string;
    selectedUsers: string;
    user: string;
    searchUsers: string;
    selectPage: string;
    unselectPage: string;
    page: string;
    previous: string;
    next: string;
    noUsersFound: string;
  };
  settings: {
    profile: string;
      profileStudio: string;
      identity: string;
      passwordStudio: string;
      security: string;
      credentials: string;
      editProfile: string;
    changePassword: string;
      oldPassword: string;
      oldPasswordPlaceholder: string;
      newPassword: string;
      newPasswordPlaceholder: string;
      confirmNewPassword: string;
      confirmNewPasswordPlaceholder: string;
      defaultPasswordWarning: string;
    modify: string;
    updateSuccess: string;
    updateError: string;
    passwordChangeSuccess: string;
    passwordChangeError: string;
  };
  auth: {
    login: string;
    emailAddress: string;
    emailPlaceholder: string;
    password: string;
    passwordPlaceholder: string;
    forgotPassword: string;
    loginButton: string;
    resetPassword: string;
    resendCode: string;
    backToLogin: string;
    confirmCode: string;
    setNewPassword: string;
    confirmPassword: string;
    passwordChanged: string;
    passwordChangedMessage: string;
    changePasswordButton: string;
    recovery: string;
    ofPassword: string;
    enterEmailDescription: string;
    enterCode: string;
    codeSentTo: string;
    codeSent: string;
    codeSendFailed: string;
  };
  validation: {
    required: string;
    shortRequired: string;
    passwordMismatch: string;
    tvaInvalid: string;
    minLength: (n: number) => string;
    maxLength: (n: number) => string;
    phoneFormat: string;
    emailInvalid: string;
    passwordMinLength: (n: number) => string;
  };
  errors: {
    errorOccurred: string;
    errorApology: string;
    authRequired: string;
    pageNotFound: string;
    pageNotFoundText: string;
    accessDenied: string;
    accessDeniedText: string;
    maintenanceTitle: string;
    maintenanceText: string;
    maintenanceSuspended: string;
    maintenanceThanks: string;
    maintenanceChip: string;
    deletionError: string;
    globalError: string;
    serverError: string;
    networkCheckMessage: string;
    unauthorized: string;
    authRequiredDetail: string;
    networkError: string;
    cannotConnectServer: string;
    genericError: string;
    sessionExpired: string;
    serviceUnavailable: string;
    unknownError: string;
    unexpectedError: string;
  };
  pdf: {
    generatePdf: string;
    chooseLanguage: string;
    french: string;
    english: string;
  };
  rawData: {
    genders: {
      male: string;
      female: string;
    };
  };
  metadata: {
    loginTitle: string;
    loginDescription: string;
    resetPasswordTitle: string;
    usersListTitle: string;
    usersListDescription: string;
    newUserTitle: string;
    newUserDescription: string;
    userDetailsTitle: string;
    userDetailsDescription: string;
    editUserTitle: string;
    editUserDescription: string;
    editProfileTitle: string;
    editProfileDescription: string;
    changePasswordTitle: string;
    changePasswordDescription: string;
    homeTitle: string;
    homeDescription: string;
    appTitle: string;
    enterCodeTitle: string;
    enterCodeDescription: string;
    setNewPasswordTitle: string;
    setNewPasswordDescription: string;
    passwordChangedTitle: string;
    passwordChangedDescription: string;
  };
  accessibility: {
    toggleDrawer: string;
    moreActions: string;
  };
};

